stages:
 - build
 - lint

nix-build:
  stage: build
  tags:
   - operations-nix
  needs: []
  script:
   - nix build
   - nix-copy-closure --include-outputs --to "$NYANTEC_BINARY_CACHE" ./result

rustfmt:
  allow_failure: true
  stage: lint
  tags:
   - operations-nix
  needs: []
  script:
   - nix develop -c cargo fmt --check
