stages:
 - build
 - test
 - lint

nix-build:
  stage: build
  tags:
   - operations-nix
  needs: []
  script:
   - nix build
   - nix-copy-closure --include-outputs --to "$NYANTEC_BINARY_CACHE" ./result

nixos-test:
  stage: test
  tags:
   - operations-nix
  needs: []
  script:
   - nix build -v -L --log-format raw .#checks.x86_64-linux.nixos-test
rustfmt:
  allow_failure: true
  stage: lint
  tags:
   - operations-nix
  needs: []
  script:
   - nix develop -c cargo fmt --check
